### ISSUE TITLE
Split package `akka.http.ccompat`

### ISSUE THREAD

**Issue by lefou** [woq-blended/akka-osgi#1]
The two artifacts `akka.parsing` and `akka.http.core` contain (disjunct) classes in the Java package  `akka.http.ccompat`. Found in version `10.1.11`. A split package is consideres bad practice, even in plain Java world. Split packages are even not possible when working with sealed packages.

We have various options here:
* Move all classes to the same package into the same artifact
* Rename one of the packages to avoid the split-package issue, preferably choosing a package name which shares the artifact name as it's prefix
* With a very good reason (is that even possible?) I think we can keep the split package, but it is the most painful and dirty solution

Related to https://github.com/akka/akka/issues/28304#issuecomment-576324672

**Comment by atooni** [comment]
We are closing the issue as resolving some of the split packages in akka itself might cause binary incompatibilities. We have found another approach to handle split-packages as outlined in the [README](https://github.com/woq-blended/akka-osgi/blob/main/Readme.adoc)
